### ISSUE TITLE
Could you tell me how to test these models after training?

### ISSUE THREAD

**Issue by benmagnifico** [iamalexkorotin/Wasserstein2GenerativeNetworks#1]
Hello iamalexkorotin :-)
I'm an undergraduate student majored in computer science.
Before mentioning what I need, firstly your code was very helpful for me.
I'm working on a problem which is how to solve optimal transport efficiently.
I find that in your notebooks, W2GN_gaussians_high_dimensions.ipynb only containing the training process.
I wonder how can I test the model after training, which is to make the model generate a transport map directly.
And could you show me the test code?
Thanks very much!

**Comment by iamalexkorotin** [comment]
Hi ben magnifico,

In W2GN_gaussians_high_dimensions.ipynb, the method uses random samples from Gaussians to learn the OT map between them. At the same time, the testing metrics (L2-UVP) are being computed. They estimate how well has the transported map has been recovered.

D is the recovered optimal (convex) potential, the method D.push(X) represents its gradient, i.e., the recovered OT map.

Hope this helps,

Best wishes,
Alex
